name: make-test
on: push
jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Step 1
        run: |
          pip install poetry
          pip install pytest
          pip install coverage
          make tests
          make coverage
      - name: Coverage report
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TESTREPORTER_ID: ${{ secrets.COVERAGE_REPORT_TEST }}
        with:
          coverageCommand: make coverage
