name: make-coverage
on: push
jobs:
  make-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dev
        run: |
          pip install poetry
          pip install pytest
          pip install coverage
          pip install pytest-cov
          pip install progress
          pip install beautifulsoup4
      - name: Coverage report
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secret.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage

