name: make-test
on: push
jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Step 1
        run: |
          pip install poetry
          make test
