name: make-coverage
on: push
jobs:
  make-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: install poetry
        run: |
          pip install poetry
          make install
      - name: Linter and test
        run: |
          make lint
          make tests
      - name: Coverage report
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secret.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage

